apiVersion: v1
kind: Namespace
metadata:
  name: netbox
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: netbox-secrets
  namespace: netbox
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-sdk
  target:
    name: netbox-secrets
    creationPolicy: Owner
    template:
      engineVersion: v2
      type: Opaque
      data:
        secret_key: "{{ .secret_key }}"
        superuser_password: "{{ .superuser_password }}"
        password: "{{ .superuser_password }}"
        api_token: ""
        username: admin
        email: admin@example.com
        email_password: ""
        db_password: "{{ .db_password }}"
        redis_password: "{{ .redis_password }}"
        api_token_pepper: "{{ .api_token_pepper }}"
        api_token_peppers.yaml: |
          API_TOKEN_PEPPERS:
            1: "{{ .api_token_pepper }}"
  data:
    - secretKey: secret_key
      remoteRef:
        key: homelab-core-netbox
        property: secret key
    - secretKey: superuser_password
      remoteRef:
        key: homelab-core-netbox
        property: superuser password
    - secretKey: db_password
      remoteRef:
        key: homelab-core-netbox
        property: db password
    - secretKey: api_token_pepper
      remoteRef:
        key: homelab-core-netbox
        property: api token pepper
    - secretKey: redis_password
      remoteRef:
        key: homelab-core-redis
        property: password
