# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: velero-backblaze-credentials
  namespace: velero
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-sdk
  target:
    name: velero-backblaze-credentials
    creationPolicy: Owner
    template:
      engineVersion: v2
      type: Opaque
      data:
        cloud: |
          [default]
          aws_access_key_id={{ .key_id }}
          aws_secret_access_key={{ .application_key }}
  data:
    - secretKey: key_id
      remoteRef:
        key: homelab-core-backblaze-velero-key
        property: key id
    - secretKey: application_key
      remoteRef:
        key: homelab-core-backblaze-velero-key
        property: credential
