apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "45"
data:
  accounts.readonly: apiKey
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "45"
data:
  policy.csv: |
    g, readonly, role:readonly
