apiVersion: v1
kind: Namespace
metadata:
  name: n8n
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: n8n-secrets
  namespace: n8n
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-sdk
  target:
    name: n8n-secrets
    creationPolicy: Owner
    template:
      engineVersion: v2
      type: Opaque
      data:
        encryption_key: "{{ .encryption_key }}"
        db_password: "{{ .db_password }}"
  data:
    - secretKey: encryption_key
      remoteRef:
        key: homelab-core-n8n
        property: encryption key
    - secretKey: db_password
      remoteRef:
        key: homelab-core-n8n
        property: db password
