apiVersion: v1
kind: Namespace
metadata:
  name: postgresql
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgresql-superuser
  namespace: postgresql
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-sdk
  target:
    name: postgresql-superuser
    creationPolicy: Owner
    template:
      engineVersion: v2
      type: kubernetes.io/basic-auth
      data:
        username: postgres
        password: "{{ .password }}"
  data:
    - secretKey: password
      remoteRef:
        key: homelab-core-postgresql
        property: password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgresql-netbox-credentials
  namespace: postgresql
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-sdk
  target:
    name: postgresql-netbox-credentials
    creationPolicy: Owner
    template:
      engineVersion: v2
      type: kubernetes.io/basic-auth
      data:
        username: netbox
        password: "{{ .password }}"
  data:
    - secretKey: password
      remoteRef:
        key: homelab-core-netbox
        property: db password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgresql-n8n-credentials
  namespace: postgresql
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-sdk
  target:
    name: postgresql-n8n-credentials
    creationPolicy: Owner
    template:
      engineVersion: v2
      type: kubernetes.io/basic-auth
      data:
        username: n8n
        password: "{{ .password }}"
  data:
    - secretKey: password
      remoteRef:
        key: homelab-core-n8n
        property: db password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgresql-mealie-credentials
  namespace: postgresql
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-sdk
  target:
    name: postgresql-mealie-credentials
    creationPolicy: Owner
    template:
      engineVersion: v2
      type: kubernetes.io/basic-auth
      data:
        username: mealie
        password: "{{ .password }}"
  data:
    - secretKey: password
      remoteRef:
        key: homelab-core-mealie
        property: db password
