# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/argoproj.io/application_v1alpha1.json
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "31"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
  sources:
    - repoURL: https://charts.longhorn.io
      chart: longhorn
      targetRevision: 1.11.1
      helm:
        releaseName: longhorn
        valueFiles:
          - $values/kubernetes/charts/longhorn/values.yaml
    - repoURL: git@github.com:your-github-user/ai-homelab-proxmox.git
      targetRevision: main
      ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
