# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/argoproj.io/application_v1alpha1.json
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-node-exporter
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "45"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: prometheus-node-exporter
  sources:
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: prometheus-node-exporter
      targetRevision: 4.53.1
      helm:
        releaseName: prometheus-node-exporter
        valueFiles:
          - $values/kubernetes/charts/prometheus-node-exporter/values.yaml
    - repoURL: git@github.com:your-github-user/ai-homelab-proxmox.git
      targetRevision: main
      ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
