apiVersion: v1
kind: Namespace
metadata:
  name: mealie
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mealie-secrets
  namespace: mealie
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-sdk
  target:
    name: mealie-secrets
    creationPolicy: Owner
    template:
      engineVersion: v2
      type: Opaque
      data:
        username: "{{ .username }}"
        password: "{{ .password }}"
        db_password: "{{ .db_password }}"
        openai_api_key: "{{ .openai_api_key }}"
        url: "{{ .url }}"
  data:
    - secretKey: username
      remoteRef:
        key: homelab-core-mealie
        property: username
    - secretKey: password
      remoteRef:
        key: homelab-core-mealie
        property: password
    - secretKey: db_password
      remoteRef:
        key: homelab-core-mealie
        property: db password
    - secretKey: openai_api_key
      remoteRef:
        key: homelab-core-mealie-openai-api
        property: credential
    - secretKey: url
      remoteRef:
        key: homelab-core-mealie
        property: url
