# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Label PRs

"on":
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      # v6
      - uses: actions/labeler@c5dadc2a45784a4b6adfcd20fea3465da3a5f904
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: .github/labeler.yaml
